#!/usr/bin/env bash
# Creates the (gitignored) env files for a deployed environment with FRESH RANDOM SECRETS,
# so stg and production can never share a password by copy-paste.
#
#   scripts/init-env.sh stg          # .env.stg and backend/.env.stg
#   scripts/init-env.sh production   # the same for production
#   scripts/init-env.sh edge         # .env.edge (domains of the shared Caddy)
#
# Never overwrites an existing file and never prints a secret. It fills in what it can
# generate (database/MinIO/JWT/webhook secrets) and wires the service hostnames used inside
# the compose network; it leaves CHANGE_ME / empty values for what only you have (Claude
# API key, LINE/Telegram credentials, domains). See docs/environments.md.
#
# INIT_ENV_ROOT overrides where the files are written (default: the repo root).
set -euo pipefail

usage() { echo "usage: $0 <stg|production|edge|name>" >&2; exit 2; }
[ $# -eq 1 ] || usage
name="$1"
[[ "$name" =~ ^[a-z][a-z0-9]{0,15}$ ]] || { echo "invalid name '$name' (lowercase letters/digits)" >&2; usage; }
command -v openssl >/dev/null || { echo "openssl is required to generate secrets" >&2; exit 1; }

root="${INIT_ENV_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
rand() { openssl rand -hex "$1"; } # hex only: safe inside connection URLs, no escaping needed

targets=()
if [ "$name" = edge ]; then
  targets=("$root/.env.edge")
else
  targets=("$root/.env.$name" "$root/backend/.env.$name")
fi
for f in "${targets[@]}"; do
  if [ -e "$f" ]; then echo "refusing to overwrite existing $f" >&2; exit 1; fi
done

umask 077 # secrets: owner-only permissions

if [ "$name" = edge ]; then
  cat > "$root/.env.edge" <<EOF
# Domains of the shared Caddy (docker-compose.edge.yml). Generated by scripts/init-env.sh.
# Point DNS A records for these at the VM BEFORE enabling an environment (Caddy gets its
# HTTPS certificates automatically on first request).
STG_APP_DOMAIN=app-stg.CHANGE_ME.example
STG_API_DOMAIN=api-stg.CHANGE_ME.example
PROD_APP_DOMAIN=app.CHANGE_ME.example
PROD_API_DOMAIN=api.CHANGE_ME.example

# Enable an environment by uncommenting its line (an environment that isn't enabled is not
# served and no certificates are requested for it).
#EDGE_STG_SITE=./deploy/edge/sites/stg.caddy
#EDGE_PROD_SITE=./deploy/edge/sites/production.caddy
EOF
  echo "created $root/.env.edge"
  echo "next: set the four domains, enable the environment(s) you deploy, then bring the edge up (docs/environments.md)"
  exit 0
fi

# Same naming as the edge's default domains (see the `edge` branch above).
if [ "$name" = production ]; then
  app_host="app.CHANGE_ME.example"; api_host="api.CHANGE_ME.example"
else
  app_host="app-$name.CHANGE_ME.example"; api_host="api-$name.CHANGE_ME.example"
fi
pg_password="$(rand 24)"
app_db_password="$(rand 24)"
minio_user="minio-$(rand 4)"
minio_password="$(rand 24)"
bucket="receipt-images"

cat > "$root/.env.$name" <<EOF
# Compose variables + infra secrets for the "$name" environment. Generated by
# scripts/init-env.sh; used with: docker compose -p receipt-$name --env-file .env.$name ...
ENV_NAME=$name
BACKEND_ENV_FILE=./backend/.env.$name

POSTGRES_USER=receipts
POSTGRES_PASSWORD=$pg_password
POSTGRES_DB=receipts_saas
# Password of the non-superuser role the API/worker connect as (created on first boot of a
# fresh volume by docker/postgres/init-app-role.sh).
APP_DB_PASSWORD=$app_db_password

# Owner role: for running migrations only. Deliberately NOT in backend/.env.$name, so the
# API and worker containers never hold it. (The deploy step that runs migrations uses this.)
OWNER_DATABASE_URL=postgresql://receipts:$pg_password@postgres:5432/receipts_saas?schema=public

MINIO_ROOT_USER=$minio_user
MINIO_ROOT_PASSWORD=$minio_password
MINIO_BUCKET=$bucket

# Frontend, BUILD-time: these are inlined into the JavaScript bundle by \`next build\`, so changing
# one needs a rebuild (up --build). NEXT_PUBLIC_API_URL is this environment's API_DOMAIN with https://.
NEXT_PUBLIC_API_URL=https://$api_host
# Optional: deep links on the "Connect chat" page (LINE add-friend URL; Telegram bot username without @).
NEXT_PUBLIC_LINE_ADD_FRIEND_URL=
NEXT_PUBLIC_TELEGRAM_BOT_USERNAME=
EOF

cat > "$root/backend/.env.$name" <<EOF
# API + worker config for the "$name" environment. Generated by scripts/init-env.sh.
# Service hostnames (postgres, redis, minio) are the ones inside this compose project.

# Non-privileged role, so Row-Level Security applies. The owner URL is intentionally absent.
APP_DATABASE_URL=postgresql://receipts_app:$app_db_password@postgres:5432/receipts_saas?schema=public

REDIS_HOST=redis
REDIS_PORT=6379

JWT_SECRET=$(rand 32)
JWT_EXPIRES_IN=7d

# Use a key of its own for this environment (Anthropic Console: separate workspace/key with a
# spend limit). On stg you may pick a cheaper model via ANTHROPIC_MODEL.
ANTHROPIC_API_KEY=CHANGE_ME
ANTHROPIC_MODEL=claude-sonnet-5

S3_ENDPOINT=minio
S3_PORT=9000
S3_USE_SSL=false
S3_ACCESS_KEY=$minio_user
S3_SECRET_KEY=$minio_password
S3_BUCKET=$bucket

# A webhook URL belongs to exactly one bot: create separate LINE / Telegram bots per
# environment. Leave empty until you have them.
LINE_CHANNEL_SECRET=
LINE_CHANNEL_ACCESS_TOKEN=
TELEGRAM_BOT_TOKEN=
TELEGRAM_WEBHOOK_SECRET=$(rand 24)

# Browser origin(s) allowed to call the API: this environment's dashboard (its APP_DOMAIN with
# https://). Required in production: the API refuses to start without it. Comma-separated.
CORS_ORIGINS=https://$app_host

PORT=3001
NODE_ENV=production
EOF

echo "created $root/.env.$name"
echo "created $root/backend/.env.$name"
echo "next: fill in CHANGE_ME / empty values (ANTHROPIC_API_KEY, the two https:// URLs, LINE/Telegram), then follow docs/environments.md"
